services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.142.0
    command: ["--config", "/etc/config/config.yaml"]
    restart: unless-stopped
    volumes:
      - ./config:/etc/config
    ports:
      - 4319:4319
      - 4320:4320
